spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pavan
    username: pavan
    password: pavan
secret.key: itsasecret
vault:
  demo.endpoint: /vault/v1/secret/demo/user/{username}
  db.endpoint: /vault/v1/secret/db/user/{username}
  primary: http://localhost:8001
  secondary : http://locahost:8082
  token : abcdef